name: Run checks

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ruff
    - name: format Python files
      run: |
        ruff format
        ruff check --fix
    - name: is_change
      id: is_change
      run: |
        git status -s > out.txt
        [ -s out.txt ]
    - name: remove out.txt
      run: |
        rm out.txt
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: Lint files
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com
        add: '*'

  tox-checks:
    needs: lint
    if: needs.lint.steps.is_change.conclusion == 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Test with tox
      run: tox

